import { formatCertificateDate } from "./certificates";

// Basic PDF construction helper (reused from certificates.ts logic)
function buildPdfDocument(objects: string[]) {
  const parts: string[] = [];
  let byteLen = 0;
  const offsets: number[] = [];

  const append = (chunk: string) => {
    parts.push(chunk);
    byteLen += Buffer.byteLength(chunk, "utf8");
  };

  append("%PDF-1.4\n");

  objects.forEach((object, index) => {
    offsets[index + 1] = byteLen;
    append(`${index + 1} 0 obj\n${object}\nendobj\n`);
  });

  const xrefOffset = byteLen;
  append(`xref\n0 ${objects.length + 1}\n`);
  append("0000000000 65535 f \n");

  for (let index = 1; index <= objects.length; index += 1) {
    append(`${String(offsets[index]).padStart(10, "0")} 00000 n \n`);
  }

  append(`trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`);
  return Buffer.from(parts.join(""), "utf8");
}

function escapePdfText(value: string) {
  return value.replaceAll("\\", "\\\\").replaceAll("(", "\\(").replaceAll(")", "\\)");
}

// Simple text wrapping helper
function wrapText(text: string, maxChars: number): string[] {
  const lines: string[] = [];
  const paragraphs = text.split("\n");

  for (const para of paragraphs) {
    if (para.trim() === "") {
      lines.push("");
      continue;
    }

    let currentLine = "";
    const words = para.split(" ");

    for (const word of words) {
      if ((currentLine + word).length > maxChars) {
        lines.push(currentLine.trim());
        currentLine = word + " ";
      } else {
        currentLine += word + " ";
      }
    }
    lines.push(currentLine.trim());
  }

  return lines;
}

export async function renderNotesPdf(title: string, markdown: string) {
  const pageWidth = 595.28; // A4 Width
  const pageHeight = 841.89; // A4 Height
  const margin = 50;
  const contentWidth = pageWidth - margin * 2;
  const maxCharsPerLine = 85;

  const pages: string[] = [];
  const lines = wrapText(markdown, maxCharsPerLine);
  
  let currentY = pageHeight - margin - 40;
  let currentLines: string[] = [];

  const addPage = (linesToDraw: string[]) => {
    const contentLines = [
      "1.0 1.0 1.0 rg", // White background
      `0 0 ${pageWidth} ${pageHeight} re f`,
      "0.1 0.1 0.1 rg", // Dark text
      `BT /F2 16 Tf ${margin} ${pageHeight - margin - 20} Td (${escapePdfText(title)}) Tj ET`, // Title
      "0.4 0.4 0.4 rg",
      `BT /F1 8 Tf ${margin} ${margin - 20} Td (Generated by AI VS ME Academy - ${formatCertificateDate(new Date())}) Tj ET`, // Footer
      "0.1 0.1 0.1 rg",
      `BT /F1 11 Tf ${margin} ${pageHeight - margin - 60} Td`, // Initial position for main text
    ];

    let y = pageHeight - margin - 60;
    for (const line of linesToDraw) {
      if (line.startsWith("# ")) {
        contentLines.push(`/F2 14 Tf 0 -20 Td (${escapePdfText(line.replace("# ", ""))}) Tj /F1 11 Tf`);
        y -= 20;
      } else if (line.startsWith("## ")) {
        contentLines.push(`/F2 12 Tf 0 -18 Td (${escapePdfText(line.replace("## ", ""))}) Tj /F1 11 Tf`);
        y -= 18;
      } else if (line.startsWith("### ")) {
        contentLines.push(`/F2 11 Tf 0 -16 Td (${escapePdfText(line.replace("### ", ""))}) Tj /F1 11 Tf`);
        y -= 16;
      } else if (line === "---") {
        contentLines.push("0 -10 Td () Tj");
        y -= 10;
      } else if (line === "") {
        contentLines.push("0 -12 Td () Tj");
        y -= 12;
      } else {
        contentLines.push(`0 -14 Td (${escapePdfText(line)}) Tj`);
        y -= 14;
      }
    }
    contentLines.push("ET");

    const contentStream = contentLines.join("\n");
    return contentStream;
  };

  // Split into pages
  let pageContent: string[] = [];
  let yCounter = pageHeight - margin - 60;

  for (const line of lines) {
    let lineHeight = 14;
    if (line.startsWith("# ")) lineHeight = 20;
    else if (line.startsWith("## ")) lineHeight = 18;
    else if (line.startsWith("### ")) lineHeight = 16;
    else if (line === "---") {
        // Force new page on --- if it's not the start
        if (pageContent.length > 0) {
            pages.push(addPage(pageContent));
            pageContent = [];
            yCounter = pageHeight - margin - 60;
            continue;
        }
    }

    if (yCounter - lineHeight < margin + 40) {
      pages.push(addPage(pageContent));
      pageContent = [];
      yCounter = pageHeight - margin - 60;
    }

    pageContent.push(line);
    yCounter -= lineHeight;
  }

  if (pageContent.length > 0) {
    pages.push(addPage(pageContent));
  }

  // PDF Objects
  const objects: string[] = [
    `<< /Type /Catalog /Pages 2 0 R >>`,
    `<< /Type /Pages /Kids [${pages.map((_, i) => `${3 + i * 2} 0 R`).join(" ")}] /Count ${pages.length} >>`,
  ];

  pages.forEach((stream, i) => {
    // Page Object
    objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Resources << /Font << /F1 ${3 + pages.length * 2} 0 R /F2 ${3 + pages.length * 2 + 1} 0 R >> >> /Contents ${4 + i * 2} 0 R >>`);
    // Content Stream
    objects.push(`<< /Length ${Buffer.byteLength(stream, "utf8")} >>\nstream\n${stream}\nendstream`);
  });

  // Fonts
  objects.push(`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`);
  objects.push(`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>`);

  return buildPdfDocument(objects);
}
